ska-sa/corr2

scripts/corr2_servlet.py
src/fxcorrelator.py

Please review changes - @brickZA @jmanley

Start working on compound sensors in corr2

---

src/dsimhost_fpga.py
src/utils.py

Add dsim host

---

README.txt
scripts/corr2_dsim_control.py
scripts/corr2_rx.py
src/dsimhost_fpga.py

Changes to work with new dsim digitiser registeres and data gating. Also do some human-scaling for sources in the FpgaDsimHost class.

Update dsim_control for new dsim options

---

src/dsimhost_fpga.py

Made all changes as stated and removed all whitespaces.

Removed whitespaces

---

scripts/corr2_dsim_control.py
src/dsimhost_fpga.py

Added additional function. 2 or 3 sin arguments input
ie: --sins "scale0" "freq0"  --sins "scale1" "freq1"

Added additional function. 2 or 3 sin arguments input

---

scripts/corr2_dsim_control.py
src/dsimhost_fpga.py

Merged master with add dsim parameters branch

Add dsim parms

---

src/fxcorrelator.py

Swapped static tap-start with dhcp-start.

---

src/fhost_fpga.py
src/host_fpga.py
src/xhost_fpga.py

@jmanley - as requested
@brickZA 
@pinsleepe 
@amartens

Updated RX and TX checks for new MKAT fpg files.

---

src/fxcorrelator.py
src/host_fpga.py

changes to initialisation routines after L3 testing in lab.

Init l3 tweaks

---

scripts/corr2_dsim_control.py

Added zero capabilities to dsim control script

Add dsim zero

---

scripts/corr2_servlet.py

CBFTASKS-252 - updated corr2_servlet logging

---

scripts/dig_init.py
src/fhost_fpga.py

minor changes to range statement

---

src/fxcorrelator.py

@paulprozesky @mmphego Some more that seemed to be missed :)

More small fixes

---

src/fxcorrelator.py

Also	commented xeng vacc timer check, to avoid startcorr to run in a loop, will uncomment it out soon

Even more small fixes

---

scripts/corr2_dsim_control.py
src/dsimhost_fpga.py

Also fix bug with --pulse-packets in corr2_dsim_control.py

Don't read 10gbe_start_ip from dsimhost config

---

README.txt
src/dsimhost_fpga.py

Required to implement increased frequency resolution since the sine-source
frequency field got too big to share a register with the scale

Update dsimhost for new dsim registers

---

scripts/corr2_sensor_servlet.py
scripts/corr2_servlet.py

New servlet for sensors

---

scripts/corr2_deprogram.py

Added reboot features

---

src/fxcorrelator_fengops.py
src/fxcorrelator_xengops.py

modified Fengine timeout

---

scripts/corr2_sensor_servlet.py
src/sensors.py

Cleaned up code in sensors

---

scripts/corr2_sensor_servlet.py
scripts/corr2_servlet.py

Added setup_sensors to corr2_servlet

---

scripts/corr2_sensor_servlet.py

Improved shutdown for sensor servlet

---

src/fhost_fpga.py
src/sensors.py

Added fft_overflow function to sensors.py

---

debug/feng_check_00_soft_reorder.py
debug/feng_check_00_unpack_spead.py
debug/feng_check_06_unpack_reorder.py
debug/fxcorr_labrts.ini
scripts/corr2_deprogram.py
scripts/corr2_servlet.py
scripts/corr2_startcorr.py
src/data_source.py
src/fhost_fpga.py
src/filthost_fpga.py
src/fxcorrelator.py
src/fxcorrelator_fengops.py
src/fxcorrelator_filterops.py
src/fxcorrelator_xengops.py
src/host_fpga.py

@brickZA - so what do we do when it won't merge automatisch?

Filter ops

---

src/fxcorrelator_filterops.py

Do not set up if not programming

---

scripts/corr2_dsim_control.py
scripts/corr2_fengine_adc_plot.py
scripts/corr2_get_baselines.py
scripts/corr2_issue_spead_metadata.py
src/fhost_fpga.py

Script work

---

scripts/corr2_dsim_control.py
src/dsimhost_fpga.py

Pulsar signal simulator for dsim CBFTASKS-236

---

src/bf_functions.py
src/bhost_fpga.py
src/dsimhost_fpga.py

@brickZA 
@paulprozesky 
@amartens

Beamformer from corr to corr2 porting (work in progress)

---

debug/feng_check_16_quant_output.py
src/fxcorrelator.py
src/utils.py

Small updates to the quant snap debug script

---

src/sensors.py

CBFTASKS-192 changed PHY to phy

---

src/bhost_fpga.py
src/sensors.py

Bf new registers

---

src/bhost_fpga.py

CBFTASKS-214 new bf_read_int function

---

src/bhost_fpga.py
src/fxcorrelator.py
src/fxcorrelator_bengops.py

Ok so this is very different to what has been merged already. I split the code into bhost_fpga and fxcorrelator_bengops. 
@brickZA 
@paulprozesky 
@amartens

Bf write functions

---

src/bhost_fpga.py

CBFTASKS-214 Object in place of FpgaHost in bhost_fpga

---

.gitignore
scripts/corr2_get_baselines.py
scripts/corr2_issue_spead_metadata.py
scripts/corr2_sensor_servlet.py
scripts/corr2_servlet.py
scripts/corr2_startcorr.py
scripts/corr2_xengine_vacc_sync.py
src/fxcorrelator.py

Make FxCorrelator log config optional CBFTASKS-287

---

scripts/corr2_get_baselines.py
scripts/corr2_sensor_servlet.py
scripts/corr2_servlet.py
scripts/corr2_snb_filter_status.py
src/fhost_fpga.py
src/filthost_fpga.py
src/fxcorrelator.py
src/fxcorrelator_fengops.py
src/fxcorrelator_filterops.py
src/fxcorrelator_xengops.py
src/utils.py

Ops in own classes so persistent vars possible.

---

src/sensors.py

CBFTASKS-298 fixed the typo

---

scripts/corr2_sensor_servlet.py
src/sensors.py

@brickZA 
@paulprozesky 
I tested the servlet and it's working as before. If Neilen could check if there is any improvement on CAM side that would be great.

CBFTASKS-299 added corr2.sensors logger

---

src/fxcorrelator_fengops.py

Fixed the logic for writing delays to fhost

---

src/sensors.py

@paulprozesky 
@brickZA 
@mmphego

CBFTASKS-307 work-around for the keyerror problems

---

src/corr_rx.py

@brickZA  Please merge changes made corr2 receiver for SPEAD2 compatibility.

Corr rx spead2

---

debug/fake_xeng_data.py
debug/fxcorr_dbertsc.ini
scripts/corr2_rx.py
scripts/corr2_servlet.py
scripts/corr2_start_stop_product.py
src/beam.py
src/bhost_fpga.py
src/corr_rx.py
src/data_product.py
src/data_source.py
src/fxcorrelator.py
src/fxcorrelator_bengops.py
src/fxcorrelator_fengops.py
src/fxcorrelator_speadops.py
src/fxcorrelator_xengops.py
src/instrument.py
src/net_address.py

@brickZA - the refactor of data products we chatted about briefly last week. I know it's a lot, but can you have a look, please?

Data product refactor

---

scripts/corr2_dsim_control.py
src/corr_rx.py
src/dsimhost_fpga.py

- AR1.5 Correlator receiver integration
- Digitiser simulator status probe
- Dsim host register bug fix

Fixes made to CBF testing rx and dsim

---

src/corr_rx.py

- Multicast subscription confirmation and improved error handling
- Dump timestamp now part of the spead accumulation(dict)

Testing Corr Rx fixes

---

src/corr_rx.py

- Verbose and improved error handling
- Duplicated confirm multicast subs function on corrRx

CBF-Tests CorrRx refactored 

---

src/corr_rx.py

- Spead accumulation human readable timestamp for debugging purposes

CBF Testing CorrRx changes

---

src/corr_rx.py

- multicast subscriptions checked globally
- improved error handling is accumulations contains a null value

Changes on testing receiver.

---

src/fhost_fpga.py
src/fxcorrelator.py

Add logic to disable F-engine in the event of CD or CT errors.

Feng ct check

---

src/fxcorrelator.py

- https://skaafrica.atlassian.net/browse/CBFTASKS-662
- BaseException.message has been deprecated as of Python 2.6 [Deprecation]

This commit fixes:

---

src/corr2LogHandlers.py

Fix for CBFTASKS-706. I'm going to leave the branch in place so that I can fix a few more logging-related issues.

Fix for CBFTASKS-706

---

src/corr2LogHandlers.py

Handle katcp log-level changes if instrument is uninitialised.

Fix CBFTASKS-716

---

scripts/corr2_rx.py

Logging handler fixed, Plot titles swapped around and adjusted subplots horizontal space by 0.5

[fix] Jira issue #CBFTASKS-718

---

src/beam.py
src/bhost_fpga.py
src/data_stream.py
src/fhost_fpga.py
src/filthost_fpga.py
src/fxcorrelator.py
src/fxcorrelator_bengops.py
src/fxcorrelator_fengops.py
src/fxcorrelator_filterops.py
src/fxcorrelator_xengops.py
src/sensors.py
src/xhost_fpga.py

Fixed it:-> Why is logging level defaulted to INFO, what if I do not want to see the info logs?

[fix] Issues were logging.INFO is hardcorded!

---

scripts/corr2_rx.py
src/bhost_fpga.py
src/fhost_fpga.py
src/fxcorrelator.py
src/fxcorrelator_bengops.py
src/sensors.py

Fixes ticket CBFTASKS-727. Git info is now reported in sensors called "git-x-0" where x can be x, f or b at the moment, and 0 can be 0 or 1, it reports both the git info of mlib_devel used to compile, and the git info of the gateware source itself.

Git info sensor

---

src/bhost_fpga.py
src/sensors.py

to show which bitstreams are running on the various hosts.

Added bitstream sensors 

---

src/fxcorrelator.py

Reverts ska-sa/corr2#147
Seems something wasn't quite thread-safe.

Revert "Thread fxops"

---

src/corr_monitoring_loop.py

The instrument monitoring loop will log the hmc reconfiguration stats
upon hmc errors. JIRA: ST-210

Log hmc reconfiguration stats upon hmc errors

---

src/sensors.py
src/xhost_fpga.py

Now calculating the MD5 Checksum on the **entire** fpg-file supplied to the F- and X-hosts.

Updates to the MD5 Checksum sensors.
